{% set name = "bitvector" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/BitVector-{{ version }}.tar.gz
  sha256: cac2fbccf11e325115827ed7be03e5fd62615227b0bbf3fa5a18a842a221839c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - BitVector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://engineering.purdue.edu/kak/dist/BitVector-3.5.0.html
  summary: A memory-efficient packed representation for bit arrays in pure Python
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MyAnoneNeko
